replicaCount: 1

image:
  repository: ghcr.io/phuongdnguyen/tempura
  pullPolicy: IfNotPresent
  tag: "sha256:892175e340645d1fd04de21cb92796d2f58ef0656b659a1b4af51595bb787c4e"

# Provide an explicit Redis address. If empty, the chart will default to the bundled Bitnami Redis service.
redisAddr: ""

service:
  type: ClusterIP
  port: 8088
  adminPort: 8089

redis:
  image:
    tag: latest
  auth:
    enabled: false
  architecture: standalone
