apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tempura.fullname" . }}
  labels:
    {{- include "tempura.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tempura.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tempura.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}@{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./app"]
          args:
            - "-listen-addr=0.0.0.0:{{ .Values.service.port }}"
            - "-admin-port={{ .Values.service.adminPort }}"
            - "-redis-addr={{ if .Values.redisAddr }}{{ .Values.redisAddr }}{{ else }}{{ .Release.Name }}-redis-master:6379{{ end }}"
          ports:
            - name: proxy
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: admin
              containerPort: {{ .Values.service.adminPort }}
              protocol: TCP
