name: Publish Helm Chart to GHCR

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  publish-helm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Update dependencies
        run: helm dependency update chart/

      - name: Package Helm Chart
        run: helm package chart/

      - name: Push Helm Chart
        run: |
          PKG_NAME=$(ls tempura-*.tgz)
          # Pushing to the /charts namespace to avoid clashing with the Docker image tags
          helm push $PKG_NAME oci://${{ env.REGISTRY }}/${{ github.repository_owner }}/charts
